name: "Update challenges on owasp-juice.shop"

on:
  push:
    branches: [ master ]
    paths: 
      - 'data/static/challenges.yml'

jobs:
  UpdateChallengesOnWebsite:
    if: github.repository == 'juice-shop/juice-shop'
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available
      with:
        token: ${{ secrets.BOT_TOKEN }}
        repository: OWASP/www-project-juice-shop
        branch: master
    - name: Update challenges.yml
      run: |
        cd _data/
        rm challenges.yml
        wget https://raw.githubusercontent.com/juice-shop/juice-shop/master/data/static/challenges.yml
    - uses: stefanzweifel/git-auto-commit-action@v4.0.0
      with:
        commit_message: "Auto-update challenges.yml from ${{ github.sha }}"
        branch: master
        commit_options: '--signoff'

        # Optional commit user and author settings
        commit_user_name: JuiceShopBot
        commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
        commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
