apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: docker.io/joshuajebaraj/gcp-app:v1
          ports:
            - containerPort: 8080
      serviceAccountName: k8s-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
